### ISSUE TITLE
StatsdClient should implement `RefUnwindSafe`

### ISSUE THREAD

**Issue by Diggsey** [tshlabs/cadence#77]
All `Sync` types should also implement `RefUnwindSafe` as the former implies the latter.

The `StatsdClient` currently does not implement `RefUnwindSafe` because it stores two trait objects:

```rust
    sink: Arc<MetricSink + Sync + Send>,
    errors: Arc<Fn(MetricError) -> () + Sync + Send>,
```

The `RefUnwindSafe` bound should be added to both of these:

```rust
    sink: Arc<MetricSink + Sync + Send + RefUnwindSafe>,
    errors: Arc<Fn(MetricError) -> () + Sync + Send + RefUnwindSafe>,
```

And then the client will automatically become `RefUnwindSafe` itself.

**Comment by 56quarters** [comment]
Thanks for the issue! I'll start looking into this. 

Seems like it may be a little tricky since `QueuingMetricSink` makes use of a `CondVar`[(1)](https://github.com/tshlabs/cadence/blob/master/src/sinks/async.rs#L272) and a Crossbeam `MsQueue`[(2)](https://github.com/tshlabs/cadence/blob/master/src/sinks/async.rs#L270) which in turn uses `UnsafeCell`. It'll be interesting to see what comes from the issue you opened in https://github.com/rust-lang/rust/issues/54768

**Comment by 56quarters** [comment]
The two places that prevent the client from not being panic safe are both in the `QueuingMetricSink`.

I've replaced the use of `CondVar` with an atomic and `thread::yield_now()` - https://github.com/tshlabs/cadence/compare/36e809d93b64e38ab64ba94ab221a3dc071396a1%5E...HEAD

The other place that prevents `QueuingMetricSink` from being panic safe is the use of a `crossbeam::MsQueue`. I believe it's safe to wrap this in `AssertUnwindSafe` based on the issue you opened https://github.com/rust-lang/rust/issues/54768. I'm currently in the process of writing a few more tests to increase my comfort with the change.
