### ISSUE TITLE
Sub-millisecond timers

### ISSUE THREAD

**Issue by parasyte** [tshlabs/cadence#98]
Rust is fast. Really really fast. When I added metrics to report how long some of the more important tasks in my service take, I find a lot of 0ms metrics:

```
service.custom.metric.time:0|ms
```

The documentation is pretty clear that the `Timer` type only supports millisecond values. And the statsd spec unfortunately expects millisecond units for timers, as whole integer values.

I'm kind of stuck in a rock and hard place; do I lie and emit values in units of microseconds (or nanoseconds) with a timer type (whose unit is milliseconds)? Or should cadence provide a nice API for providing `Duration` values to the `Histogrammed` trait?

```rust
let time = Instant::now();
do_something_slow();
let duration = time.elapsed();

client.histogram_duration("custom.metric.time", duration).send();
```

And similar with `histogram_duration_with_tags()` ...

If this is a good idea, would the unit value of nanoseconds make sense for general purpose uses?

**Comment by 56quarters** [comment]
Sounds like a good idea! I think nanoseconds make sense for this.

Looking at the [`Duration` docs](https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_nanos), it looks like `Duration::as_nanos()` returns a `u128` but histograms are `u64`. Doing some quick math, it seems like you can represent a duration of almost 600 years with nanoseconds in a `u64` so I don't think that'll be a problem in practice.

The implementation of this would probably end up looking a lot like way `Duration`s are handled for the `Timed` trait in terms of which methods delegate to which. This would also be a good chance to use the `Duration::as_millis()` method for timers (since they didn't exist when originally implemented).

I'll probably take a shot at this shortly.

**Comment by parasyte** [comment]
I did the same thing; `duration.as_nanos() as u64`. It limits the duration to about 544 years. That seems reasonable!

Currently using this with `histrogram_with_tags` and our DataDog dashboards are looking great, now. I'll be happy to update it all after this features goes out in a future release.
